const ExcelJS = require('exceljs');

const moneyFormat = '$#,##0;-$#,##0';
const percentFormat = '0.0%';
const dateFormat = 'dd/mm/yyyy';
const dateTimeFormat = 'dd/mm/yyyy hh:mm';
const valueDate = (value) => value ? new Date(value) : null;
const safe = (value) => value === undefined || value === null || value === '' ? '—' : value;

function addSheet(workbook, name, columns, rows) {
  const sheet = workbook.addWorksheet(name);
  sheet.columns = columns.map(([header, key, width, numFmt]) => ({ header, key, width, style: numFmt ? { numFmt } : undefined }));
  if (rows.length) sheet.addRows(rows); else sheet.addRow({ [columns[0][1]]: 'Sin datos para el periodo seleccionado.' });
  sheet.views = [{ state: 'frozen', ySplit: 1 }];
  sheet.autoFilter = { from: 'A1', to: `${String.fromCharCode(64 + Math.min(columns.length, 26))}1` };
  sheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } }; sheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF073D31' } }; sheet.getRow(1).alignment = { vertical: 'middle' }; sheet.getRow(1).height = 23;
  sheet.eachRow((row, index) => { if (index > 1) row.alignment = { vertical: 'top' }; });
  return sheet;
}

function makeWorkbook(data, { from, to, lowStockThreshold = 3 }) {
  const workbook = new ExcelJS.Workbook(); workbook.creator = 'NARI Admin'; workbook.created = new Date(); workbook.properties.date1904 = false;
  const sales = Number(data.totals.sales || 0); const orderCount = Number(data.totals.orders || 0); const units = Number(data.totals.units || 0); const cost = Number(data.financial.productCost || 0); const discounts = Number(data.financial.discounts || 0); const fees = Number(data.financial.paymentFees || 0); const shipping = Number(data.financial.shippingCosts || 0); const margin = sales - cost - fees - shipping - Number(data.financial.refunds || 0);
  const lowStockCount = data.inventory.filter((product) => Number(product.stock) > 0 && Number(product.stock) <= Number(product.minimumStock ?? lowStockThreshold)).length; const outOfStockCount = data.inventory.filter((product) => Number(product.stock) === 0).length;
  const summary = workbook.addWorksheet('Resumen'); summary.columns = [{ header: 'Métrica', key: 'metric', width: 34 }, { header: 'Valor', key: 'value', width: 20, style: { numFmt: moneyFormat } }]; summary.addRows([{ metric: 'Periodo', value: `${from.slice(0, 10)} — ${to.slice(0, 10)}` }, { metric: 'Ventas totales', value: sales }, { metric: 'Pedidos válidos', value: orderCount }, { metric: 'Unidades vendidas', value: units }, { metric: 'Ticket promedio', value: orderCount ? sales / orderCount : 0 }, { metric: 'Clientes únicos', value: new Set(data.orders.map((order) => order.email).filter(Boolean)).size }, { metric: 'Costo mercancía vendida', value: cost }, { metric: 'Utilidad bruta estimada', value: sales - cost }, { metric: 'Descuentos', value: discounts }, { metric: 'Comisiones de pago', value: fees || 'Sin datos' }, { metric: 'Envíos asumidos por NARI', value: shipping || 'Sin datos' }, { metric: 'Margen de contribución estimado', value: margin }, { metric: 'Margen bruto %', value: sales ? (sales - cost) / sales : 0 }, { metric: 'Margen contribución %', value: sales ? margin / sales : 0 }, { metric: 'Productos activos', value: Number(data.inventoryTotals.active || 0) }, { metric: 'Unidades actuales', value: Number(data.inventoryTotals.units || 0) }, { metric: 'Valor inventario a costo', value: Number(data.inventoryTotals.costValue || 0) }, { metric: 'Valor potencial de venta', value: Number(data.inventoryTotals.saleValue || 0) }, { metric: 'Productos con stock bajo', value: lowStockCount }, { metric: 'Productos agotados', value: outOfStockCount }, { metric: 'Nota', value: 'Valores operativos estimados. No sustituyen la información contable oficial.' }]); summary.views = [{ state: 'frozen', ySplit: 1 }]; summary.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } }; summary.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF073D31' } }; summary.getColumn(2).eachCell((cell, row) => { if ([2, 5, 7, 8, 9, 10, 11, 12, 17, 18].includes(row)) cell.numFmt = moneyFormat; if ([13, 14].includes(row)) cell.numFmt = percentFormat; });

  addSheet(workbook, 'Pedidos', [['ID pedido', 'id', 18], ['Fecha', 'date', 15, dateTimeFormat], ['Cliente', 'customer', 24], ['Email', 'email', 28], ['Teléfono', 'phone', 17], ['Ciudad', 'city', 18], ['Departamento', 'department', 18], ['Unidades', 'units', 11], ['Subtotal productos', 'subtotal', 17, moneyFormat], ['Descuento', 'discount', 14, moneyFormat], ['Envío cobrado', 'shippingCharged', 16, moneyFormat], ['Total pedido', 'total', 16, moneyFormat], ['Proveedor envío', 'provider', 18], ['Número guía', 'tracking', 20], ['Estado', 'status', 15], ['Costo mercancía', 'cost', 16, moneyFormat], ['Costo envío asumido', 'shippingCost', 18, moneyFormat], ['Utilidad estimada', 'profit', 16, moneyFormat], ['Margen %', 'margin', 12, percentFormat]], data.orders.map((order) => { const orderItems = data.items.filter((item) => item.orderId === order.id); const itemCost = orderItems.reduce((sum, item) => sum + Number(item.unitCost ?? item.currentCost ?? 0) * Number(item.quantity), 0); const productTotal = orderItems.reduce((sum, item) => sum + Number(item.unitPrice) * Number(item.quantity), 0); const profit = productTotal - itemCost; return { id: order.id, date: valueDate(order.createdAt), customer: `${order.firstName || ''} ${order.lastName || ''}`.trim() || 'Cliente no disponible', email: safe(order.email), phone: safe(order.phone), city: safe(order.city), department: safe(order.department), units: orderItems.reduce((sum, item) => sum + Number(item.quantity), 0), subtotal: Number(order.subtotal ?? productTotal), discount: Number(order.discountTotal || 0), shippingCharged: Number(order.shippingTotal || 0), total: Number(order.total || 0), provider: safe(order.shippingProvider), tracking: safe(order.trackingNumber), status: order.status, cost: itemCost, shippingCost: Number(order.shippingCost || 0), profit, margin: productTotal ? profit / productTotal : 0 }; }));
  addSheet(workbook, 'Productos vendidos', [['Pedido', 'orderId', 18], ['Fecha', 'date', 15, dateTimeFormat], ['SKU', 'sku', 18], ['Producto', 'productName', 34], ['Marca', 'brand', 18], ['Proveedor', 'supplier', 18], ['Categoría', 'category', 20], ['Cantidad', 'quantity', 12], ['Precio unitario', 'unitPrice', 16, moneyFormat], ['Venta bruta', 'gross', 16, moneyFormat], ['Costo unitario histórico', 'unitCost', 20, moneyFormat], ['Costo total', 'cost', 16, moneyFormat], ['Utilidad bruta', 'profit', 16, moneyFormat], ['Margen %', 'margin', 12, percentFormat], ['Cliente', 'customer', 24], ['Ciudad', 'city', 18]], data.items.map((item) => ({ orderId: item.orderId, date: valueDate(item.createdAt), sku: safe(item.sku), productName: item.productName, brand: safe(item.brand), supplier: safe(item.supplier), category: safe(item.category), quantity: Number(item.quantity), unitPrice: Number(item.unitPrice), gross: Number(item.unitPrice) * Number(item.quantity), unitCost: Number(item.unitCost ?? item.currentCost ?? 0), cost: Number(item.unitCost ?? item.currentCost ?? 0) * Number(item.quantity), profit: (Number(item.unitPrice) - Number(item.unitCost ?? item.currentCost ?? 0)) * Number(item.quantity), margin: Number(item.unitPrice) ? (Number(item.unitPrice) - Number(item.unitCost ?? item.currentCost ?? 0)) / Number(item.unitPrice) : 0, customer: `${item.firstName || ''} ${item.lastName || ''}`.trim() || 'Cliente no disponible', city: safe(item.city) })));
  addSheet(workbook, 'Rentabilidad pedidos', [['Fecha', 'date', 15, dateFormat], ['Pedido', 'id', 18], ['Venta productos', 'sales', 17, moneyFormat], ['Descuento', 'discount', 14, moneyFormat], ['Venta neta', 'netSales', 16, moneyFormat], ['Costo mercancía', 'cost', 16, moneyFormat], ['Utilidad bruta', 'grossProfit', 16, moneyFormat], ['Comisión pasarela', 'fee', 18, moneyFormat], ['Envío asumido NARI', 'shippingCost', 18, moneyFormat], ['Margen contribución', 'contribution', 19, moneyFormat], ['Margen %', 'margin', 12, percentFormat]], data.orders.map((order) => { const items = data.items.filter((item) => item.orderId === order.id); const productSales = items.reduce((sum, item) => sum + Number(item.unitPrice) * Number(item.quantity), 0); const itemCost = items.reduce((sum, item) => sum + Number(item.unitCost ?? item.currentCost ?? 0) * Number(item.quantity), 0); const contribution = productSales - itemCost - Number(order.paymentFee || 0) - Number(order.shippingCost || 0); return { date: valueDate(order.createdAt), id: order.id, sales: productSales, discount: Number(order.discountTotal || 0), netSales: Number(order.total || 0), cost: itemCost, grossProfit: productSales - itemCost, fee: Number(order.paymentFee || 0), shippingCost: Number(order.shippingCost || 0), contribution, margin: productSales ? contribution / productSales : 0 }; }));
  addSheet(workbook, 'Rentabilidad productos', [['SKU', 'sku', 18], ['Producto', 'productName', 34], ['Marca', 'brand', 18], ['Proveedor', 'supplier', 18], ['Categoría', 'category', 20], ['Unidades vendidas', 'units', 17], ['Pedidos', 'orders', 12], ['Ventas brutas', 'grossSales', 16, moneyFormat], ['Ventas netas', 'sales', 16, moneyFormat], ['Costo mercancía', 'cost', 16, moneyFormat], ['Utilidad bruta', 'profit', 16, moneyFormat], ['Margen bruto %', 'margin', 15, percentFormat], ['Ranking utilidad', 'profitRank', 16]], data.productRows.map((row, index) => ({ sku: safe(row.sku), productName: row.productName, brand: row.brand, supplier: safe(row.supplier), category: row.category, units: row.units, orders: row.orders, grossSales: row.grossSales, sales: row.sales, cost: row.cost, profit: row.profit, margin: row.margin, profitRank: index + 1 })));
  addSheet(workbook, 'Inventario', [['SKU', 'sku', 18], ['Marca', 'brand', 18], ['Producto', 'name', 34], ['Proveedor', 'supplier', 18], ['Categoría', 'category', 20], ['Costo actual', 'cost', 16, moneyFormat], ['Precio venta actual', 'price', 18, moneyFormat], ['Stock actual', 'stock', 14], ['Stock mínimo', 'minimumStock', 14], ['Estado stock', 'stockStatus', 16], ['Valor a costo', 'costValue', 16, moneyFormat], ['Valor potencial venta', 'saleValue', 20, moneyFormat]], data.inventory.map((product) => ({ sku: safe(product.sku), brand: product.brand, name: product.name, supplier: safe(product.supplier), category: product.category, cost: Number(product.cost || 0), price: Number(product.price || 0), stock: Number(product.stock || 0), minimumStock: Number(product.minimumStock ?? lowStockThreshold), stockStatus: product.stock === 0 ? 'Agotado' : product.stock <= Number(product.minimumStock ?? lowStockThreshold) ? 'Stock bajo' : 'Disponible', costValue: Number(product.stock || 0) * Number(product.cost || 0), saleValue: Number(product.stock || 0) * Number(product.price || 0) })));
  addSheet(workbook, 'Movimientos inventario', [['Fecha', 'date', 15, dateTimeFormat], ['SKU', 'sku', 18], ['Producto', 'productName', 34], ['Tipo movimiento', 'type', 18], ['Cantidad', 'quantity', 12], ['Stock anterior', 'stockBefore', 15], ['Stock posterior', 'stockAfter', 15], ['Motivo', 'reason', 24], ['Referencia', 'reference', 18], ['Pedido relacionado', 'orderId', 20], ['Compra relacionada', 'purchaseId', 20], ['Usuario responsable', 'performedBy', 22], ['Notas', 'notes', 30]], data.movements.map((movement) => ({ date: valueDate(movement.createdAt), sku: safe(movement.sku), productName: safe(movement.productName), type: movement.type, quantity: Number(movement.quantity), stockBefore: movement.stockBefore ?? '—', stockAfter: movement.stockAfter ?? '—', reason: safe(movement.reason || movement.description), reference: safe(movement.reference), orderId: safe(movement.orderId), purchaseId: safe(movement.purchaseId), performedBy: safe(movement.performedBy), notes: safe(movement.notes) })));
  addSheet(workbook, 'Clientes', [['Cliente', 'customer', 26], ['Email', 'email', 30], ['Teléfono', 'phone', 18], ['Ciudad', 'city', 18], ['Departamento', 'department', 18], ['Primera compra', 'firstPurchase', 15, dateFormat], ['Última compra', 'lastPurchase', 15, dateFormat], ['Pedidos', 'orders', 12], ['Total gastado', 'spent', 16, moneyFormat], ['Ticket promedio', 'average', 16, moneyFormat], ['Tipo cliente', 'customerType', 18]], data.customers.map((customer) => ({ customer: `${customer.firstName} ${customer.lastName}`, email: customer.email, phone: customer.phone, city: safe(customer.city), department: safe(customer.department), firstPurchase: valueDate(customer.firstPurchaseAt), lastPurchase: valueDate(customer.lastPurchaseAt), orders: customer.orderCount, spent: customer.totalPurchased, average: customer.orderCount ? customer.totalPurchased / customer.orderCount : 0, customerType: customer.orderCount > 1 ? 'Recurrente' : 'Nuevo' })));
  addSheet(workbook, 'Compras', [['Estado', 'status', 24]], []); addSheet(workbook, 'Proveedores', [['Estado', 'status', 24]], []);
  addSheet(workbook, 'Descuentos', [['Fecha', 'date', 15, dateTimeFormat], ['Pedido', 'orderId', 18], ['Cliente', 'customer', 26], ['Valor pedido antes descuento', 'before', 24, moneyFormat], ['Descuento aplicado', 'discount', 20, moneyFormat], ['Total final', 'total', 16, moneyFormat], ['Porcentaje efectivo', 'rate', 20, percentFormat]], data.orders.filter((order) => Number(order.discountTotal || 0) > 0).map((order) => ({ date: valueDate(order.createdAt), orderId: order.id, customer: `${order.firstName || ''} ${order.lastName || ''}`.trim() || 'Cliente no disponible', before: Number(order.total || 0) + Number(order.discountTotal || 0), discount: Number(order.discountTotal || 0), total: Number(order.total || 0), rate: Number(order.total || 0) + Number(order.discountTotal || 0) ? Number(order.discountTotal || 0) / (Number(order.total || 0) + Number(order.discountTotal || 0)) : 0 })));
  addSheet(workbook, 'Referidos', [['Estado', 'status', 24]], []);
  addSheet(workbook, 'Envíos', [['Pedido', 'orderId', 18], ['Fecha', 'date', 15, dateTimeFormat], ['Cliente', 'customer', 26], ['Ciudad', 'city', 18], ['Departamento', 'department', 18], ['Transportadora', 'provider', 20], ['Número guía', 'tracking', 22], ['Costo real envío', 'realCost', 18, moneyFormat], ['Envío cobrado cliente', 'charged', 20, moneyFormat], ['Envío asumido NARI', 'assumed', 20, moneyFormat], ['Estado envío', 'status', 18]], data.orders.map((order) => ({ orderId: order.id, date: valueDate(order.createdAt), customer: `${order.firstName || ''} ${order.lastName || ''}`.trim() || 'Cliente no disponible', city: safe(order.city), department: safe(order.department), provider: safe(order.shippingProvider), tracking: safe(order.trackingNumber), realCost: Number(order.shippingCost || 0), charged: Number(order.shippingTotal || 0), assumed: Math.max(Number(order.shippingCost || 0) - Number(order.shippingTotal || 0), 0), status: order.status })));
  addSheet(workbook, 'Resumen clientes', [['Métrica', 'metric', 30], ['Cantidad', 'count', 16]], [
    { metric: 'Clientes totales', count: data.customers.length },
    { metric: 'Clientes con cuenta', count: data.customers.filter((customer) => Boolean(customer.authUserId)).length },
    { metric: 'Clientes sin cuenta', count: data.customers.filter((customer) => !customer.authUserId).length },
    { metric: 'Carritos abandonados activos', count: Number(data.abandonedCarts || 0) },
  ]);
  return workbook;
}

module.exports = { makeWorkbook };
