// Datos proporcionados por el usuario. Se usan solo para actualizar productos existentes por SKU.
module.exports = [
  {
    "sku": "NAR-ANU-H77T-250ML",
    "name": "Anua Heartleaf 77 Soothing Toner 250 ml",
    "brand": "Anua",
    "category": "Tónico",
    "concerns": "Sensibilidad · Hidratación · Rojeces",
    "skinTypes": "Todas. Especialmente sensible, mixta, grasa y con tendencia acneica. También funciona perfectamente en piel normal o seca que quiera un tónico ligero.",
    "description": "Tónico acuoso calmante formulado alrededor de heartleaf o Houttuynia cordata. Ayuda a rehidratar la piel inmediatamente después de la limpieza, reducir la sensación de tirantez y mantener una piel equilibrada sin añadir una capa pesada o grasa. Es especialmente útil en rutinas sencillas para piel reactiva, congestionada o que busca hidratación ligera. Anua lo posiciona para todo tipo de piel y piel con tendencia acneica. Anua US",
    "audience": "Para alguien que siente la piel sensible, caliente, incómoda o deshidratada después de lavarse; también para quien quiere introducir un tónico sencillo sin usar ácidos fuertes.",
    "skinBenefits": "Aporta humectación, ayuda a calmar y prepara la piel para que los tratamientos posteriores se distribuyan mejor.",
    "howToUse": "Mañana: limpieza → Heartleaf 77 Toner → sérum → hidratante si se necesita → protector solar. Noche: doble limpieza si hubo protector/maquillaje → limpiador → Heartleaf 77 Toner → tratamiento → hidratante. Puede aplicarse con las manos o con algodón.",
    "precautions": "Aunque es un producto generalmente suave, introducir gradualmente si la piel está muy reactiva. Suspender si aparece irritación persistente. No sustituye una hidratante en piel seca.",
    "fullIngredients": "Houttuynia Cordata Flower/Leaf/Stem Water, Water, 1,2-Hexanediol, Glycerin, Betaine, Butylene Glycol, Isopentyldiol, Panthenol, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Disodium EDTA, Tromethamine, Centella Asiatica Extract, Arctium Lappa Root Extract, Phellinus Linteus Extract, Portulaca Oleracea Extract, Chamomilla Recutita (Matricaria) Flower Extract, Vitex Agnus-Castus Extract, Sodium Hyaluronate, Hydroxypropyltrimonium Hyaluronate, Hydrolyzed Hyaluronic Acid, Sodium Acetylated Hyaluronate, Hyaluronic Acid, Sodium Hyaluronate Crosspolymer, Potassium Hyaluronate. Anua US"
  },
  {
    "sku": "NAR-ANU-QPDF-150ML",
    "name": "Anua Heartleaf Quercetinol Pore Deep Cleansing Foam 150 ml",
    "brand": "Anua",
    "category": "Limpiador diario",
    "concerns": "Sebo · Poros · Imperfecciones",
    "skinTypes": "Grasa, mixta y acneica principalmente. Normal puede usarlo. En piel seca o muy sensible preferiría un limpiador más sencillo si genera tirantez.",
    "description": "Limpiador espumoso pensado para retirar suciedad, exceso de grasa y residuos acumulados dentro y alrededor de los poros. Combina Heartleaf y Quercetinol con exfoliantes como betaína salicilato y LHA, por lo que ofrece algo más de trabajo sobre sebo y textura que un limpiador básico. Es una opción especialmente interesante para personas con piel grasa, puntos negros o tendencia a congestión. Anua Global",
    "audience": "Personas que terminan el día con mucho brillo, sienten poros congestionados, tienen puntos negros o quieren un segundo paso de doble limpieza con mayor capacidad de arrastre.",
    "skinBenefits": "Limpia, ayuda a retirar sebo acumulado y realiza una exfoliación superficial suave.",
    "howToUse": "Noche con protector/maquillaje: aceite o bálsamo → Quercetinol Foam → tónico → tratamiento → crema. Mañana puede utilizarse solo si la piel lo tolera. Haz espuma con agua antes de masajear.",
    "precautions": "Contiene derivados exfoliantes del ácido salicílico y aceite de eucalipto. En piel extremadamente sensible, reseca o irritada conviene usarlo con menor frecuencia. Evitar combinar una rutina excesivamente exfoliante si también se usan AHA/BHA fuertes.",
    "fullIngredients": "Houttuynia Cordata Flower/Leaf/Stem Water, Glycerin, Sodium Cocoyl Glycinate, Water, Sodium Lauroyl Glutamate, Disodium Cocoamphodiacetate, Coco-Glucoside, Decyl Glucoside, Hectorite, Sodium Chloride, 1,2-Hexanediol, Betaine Salicylate, Potassium Benzoate, Houttuynia Cordata Powder, Polyquaternium-67, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Butylene Glycol, Gardenia Florida Fruit Extract, Dextrin, Disodium EDTA, Eucalyptus Globulus Leaf Oil, Ethylhexylglycerin, Sodium Acetate, Isopropyl Alcohol, Pinus Palustris Leaf Extract, Ulmus Davidiana Root Extract, Oenothera Biennis Flower Extract, Pueraria Lobata Root Extract, Pentylene Glycol, Capryloyl Salicylic Acid, Tocopherol, Hydrolyzed Hyaluronic Acid, Hyaluronic Acid, Hydrolyzed Sodium Hyaluronate, Sodium Hyaluronate, Potassium Hyaluronate, Hydroxypropyltrimonium Hyaluronate, Sodium Hyaluronate Crosspolymer, Sodium Acetylated Hyaluronate, Quercetin. Anua Global"
  },
  {
    "sku": "NAR-ANU-P70N-030ML",
    "name": "Anua Peach 70 Niacin Serum 30 ml",
    "brand": "Anua",
    "category": "Sérum / activo",
    "concerns": "Manchas · Luminosidad · Tono desigual",
    "skinTypes": "Normal, seca, mixta y grasa. Sensible puede probarlo gradualmente.",
    "description": "Sérum iluminador formulado con extracto de durazno, 5% de niacinamida y otros ingredientes orientados a mejorar luminosidad y uniformidad, incluyendo alpha-arbutin y un derivado estable de vitamina C. Al mismo tiempo incorpora humectantes, ácido hialurónico, pantenol y ceramida para evitar que el enfoque antimanchas dependa únicamente de ingredientes exfoliantes. Ulta Beauty",
    "audience": "Piel apagada, marcas post-acné, tono poco uniforme o alguien que quiere empezar un tratamiento de luminosidad relativamente sencillo.",
    "skinBenefits": "Ayuda a mejorar visualmente manchas, luminosidad y uniformidad mientras aporta hidratación.",
    "howToUse": "Limpieza → tónico → 2-3 gotas de Peach Serum → hidratante → SPF por la mañana. Puede usarse AM/PM.",
    "precautions": "Contiene fragancia y betaine salicylate. En piel muy sensible introducir gradualmente. Con cualquier tratamiento antimanchas, el protector solar diario es esencial.",
    "fullIngredients": "Prunus Persica (Peach) Fruit Extract, Glycerin, Niacinamide, Butylene Glycol, Diethoxyethyl Succinate, Water, 1,2-Hexanediol, Lactobacillus Ferment, Sodium Hyaluronate, Sphingomonas Ferment Extract, Alpha-Arbutin, Melia Azadirachta Flower Extract, Ocimum Sanctum Leaf Extract, Melia Azadirachta Leaf Extract, Carthamus Tinctorius Seed Oil, Salvia Hispanica Seed Oil, Curcuma Longa Root Extract, Corallina Officinalis Extract, Hydrolyzed Hyaluronic Acid, Chamaecyparis Obtusa Leaf Extract, Prunus Persica Flower Extract, Centella Asiatica Extract, Artemisia Princeps Leaf Extract, Pentylene Glycol, Polyglyceryl-10 Laurate, Betaine Salicylate, Sodium Phytate, Cellulose, Caprylic/Capric Triglyceride, Hydrogenated Lecithin, Panthenol, Polyglutamic Acid, Linoleic Acid, Linolenic Acid, Polyglyceryl-10 Oleate, Sucrose Palmitate, Cyanocobalamin, 3-O-Ethyl Ascorbic Acid, Ceramide NP, Lactobionic Acid, Asiaticoside, Madecassic Acid, Asiatic Acid, Xanthan Gum, Fragrance (Parfum). Anua Global"
  },
  {
    "sku": "NAR-DRA-345R-050ML",
    "name": "Dr. Althea 345 Relief Cream 50 ml",
    "brand": "Dr. Althea",
    "category": "Hidratante",
    "concerns": "Reparación barrera · Sensibilidad · Post-acné",
    "skinTypes": "Todas; especialmente mixta, grasa, sensible y acneica.",
    "description": "Hidratante ligera de enfoque calmante y reparador que combina niacinamida, pantenol, beta-glucano, ceramida NP, centella, madecassoside y humectantes. Está diseñada para mantener hidratación y confort sin recurrir a una crema excesivamente pesada, por lo que encaja especialmente bien en piel que presenta imperfecciones pero al mismo tiempo necesita cuidar su barrera. La versión actual está probada como no comedogénica. DR.ALTHEA",
    "audience": "Personas con acné o marcas que sienten que las cremas reparadoras tradicionales son demasiado pesadas.",
    "skinBenefits": "Hidrata, refuerza la barrera y ayuda con aspecto de rojeces y marcas.",
    "howToUse": "Como último paso antes del protector solar por la mañana o último paso nocturno.",
    "precautions": "Tiene Tea Tree Leaf Water; aunque la fórmula es para piel sensible, cualquier persona particularmente reactiva debe hacer prueba localizada.",
    "fullIngredients": "Aqua, Melaleuca Alternifolia Leaf Water, Propanediol, Glycerin, 1,2-Hexanediol, Hydrogenated Polydecene, Vinyl Dimethicone, C14-22 Alcohols, Niacinamide, Caprylic/Capric Triglyceride, Panthenol, Dicaprylyl Carbonate, Butylene Glycol, Ammonium Acryloyldimethyltaurate/VP Copolymer, Caprylyl Methicone, Polymethylsilsesquioxane, C12-20 Alkyl Glucoside, Hydroxyacetophenone, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Polyquaternium-51, Ethylhexylglycerin, Tromethamine, Sodium Hyaluronate, Sodium Stearoyl Glutamate, Coptis Japonica Root Extract, Centella Asiatica Leaf Water, Beta-Glucan, Resveratrol, Hydrolyzed Hyaluronic Acid, Camellia Sinensis Leaf Water, Tocopherol, Madecassoside, Sodium DNA, Centella Asiatica Extract, Ceramide NP, Tannic Acid, Disodium EDTA, Sodium Phytate. DR.ALTHEA"
  },
  {
    "sku": "NAR-DRA-PGCB-050ML",
    "name": "Dr. Althea Pure Grinding Cleansing Balm 50 ml",
    "brand": "Dr. Althea",
    "category": "Doble limpieza / primer paso",
    "concerns": "Limpieza · Protector solar · Maquillaje",
    "skinTypes": "Todas, incluyendo sensible.",
    "description": "Bálsamo limpiador de textura sólida que se transforma en aceite al masajear y posteriormente en una emulsión lechosa al añadir agua. Su función principal es disolver protector solar, maquillaje, grasa y productos resistentes antes del limpiador acuoso, sin depender de detergentes agresivos. La fórmula es corta e incorpora aceites vegetales, centella y madecassoside. DR.ALTHEA",
    "audience": "Cualquier persona que use SPF diariamente o maquillaje.",
    "skinBenefits": "Disuelve componentes oleosos que un limpiador acuoso puede retirar con mayor dificultad.",
    "howToUse": "Rostro y manos secos → bálsamo → masaje → añadir agua y emulsionar → enjuagar → limpiador acuoso.",
    "precautions": "No aplicar como una crema que permanezca sobre la piel. Enjuagar completamente. Si entra en ojos, aclarar con abundante agua.",
    "fullIngredients": "Cetyl Ethylhexanoate, Synthetic Wax, Caprylic/Capric Triglyceride, Sorbitan Sesquioleate, PEG-10 Isostearate, PEG-20 Glyceryl Triisostearate, Caprylyl Glycol, Ethylhexylglycerin, Camellia Sinensis Seed Oil, Vitis Vinifera (Grape) Seed Oil, Madecassoside, Centella Asiatica Extract, Asiaticoside, Water. DR.ALTHEA"
  },
  {
    "sku": "NAR-KSE-1988E-030ML",
    "name": "KSECRET Seoul 1988 Eye Cream Retinal Liposome 4% + Fermented Bean 30 ml",
    "brand": "KSECRET",
    "category": "Contorno / activo",
    "concerns": "Antiedad · Arrugas · Firmeza",
    "skinTypes": "Normal, seca, mixta y grasa. Sensible solo con introducción progresiva.",
    "description": "Tratamiento para el contorno de los ojos basado en retinal encapsulado, niacinamida, adenosina, bakuchiol, péptidos y fermentos. Está orientado principalmente a líneas finas, textura y pérdida de firmeza. La encapsulación busca mejorar estabilidad y tolerancia del retinal, pero sigue siendo un retinoide y por tanto debe introducirse lentamente. What's In My Jar",
    "audience": "Persona que ya empieza a notar líneas finas, textura o pérdida de firmeza alrededor de los ojos.",
    "skinBenefits": "Favorece renovación cutánea y mejora gradualmente apariencia de líneas y firmeza.",
    "howToUse": "Noche: limpieza → tónico → sérum hidratante → cantidad muy pequeña del eye cream alrededor del hueso orbital → hidratante. Empieza 2 noches por semana y aumenta según tolerancia.",
    "precautions": "Retinoide. Evitar párpado móvil y contacto directo con ojos. Usar SPF cada mañana. Por prudencia, los retinoides tópicos se evitan durante embarazo; consulta profesional en embarazo/lactancia. No es necesario combinarlo la misma noche con otros retinoides. Importante: “Retinal Liposome 4%” describe el complejo liposomal, no significa necesariamente 4% de retinal puro.",
    "fullIngredients": "Water, Glycerin, Dipropylene Glycol, Caprylic/Capric Triglyceride, 1,2-Hexanediol, Butylene Glycol Dicaprylate/Dicaprate, Niacinamide, Pentaerythrityl Tetraethylhexanoate, Cetearyl Alcohol, Butylene Glycol, Cetearyl Olivate, Sorbitan Olivate, Hydrogenated Lecithin, Macadamia Ternifolia Seed Oil, Carbomer, Tromethamine, Propanediol, Glyceryl Stearate, Cholesterol, Polyglyceryl-10 Oleate, Ethylhexylglycerin, Adenosine, Brassica Campestris Sterols, Phytosteryl/Behenyl/Octyldodecyl Lauroyl Glutamate, Retinal, Silica, Disodium EDTA, Aluminum/Magnesium Hydroxide Stearate, Lactobacillus/Panax Ginseng Root Ferment Filtrate, Lactobacillus/Rice Ferment, Lactobacillus/Soybean Ferment Extract, Saccharomyces/Coix Lacryma-Jobi Ma-Yuen Seed Ferment Filtrate, Saccharomyces/Potato Extract Ferment Filtrate, Tocopherol, Potassium Cetyl Phosphate, Pentaerythrityl Tetra-Di-T-Butyl Hydroxyhydrocinnamate, Sodium Hyaluronate, Arctium Lappa Root Extract, Cnidium Officinale Root Extract, Dioscorea Japonica Root Extract, Paeonia Suffruticosa Root Extract, Rehmannia Chinensis Root Extract, 3-O-Ethyl Ascorbic Acid, Bakuchiol, SH-Oligopeptide-1, SH-Oligopeptide-2, SH-Polypeptide-1. Walmart.ca"
  },
  {
    "sku": "NAR-KSE-1988S-030ML",
    "name": "KSECRET Seoul 1988 Serum Retinal Liposome 2% + Black Ginseng 30 ml",
    "brand": "KSECRET",
    "category": "Sérum / activo",
    "concerns": "Antiedad · Arrugas · Textura",
    "skinTypes": "Normal, mixta, grasa y seca. Sensible debe empezar lentamente.",
    "description": "Sérum nocturno antiedad que combina retinal liposomado con ginseng, niacinamida, adenosina, bakuchiol, antioxidantes y péptidos. Está pensado para acelerar gradualmente la renovación superficial, mejorar textura, líneas finas, firmeza y uniformidad del tono. Es uno de los tratamientos más activos de tu catálogo y debe venderse con educación de uso. SOMI",
    "audience": "Alguien que quiere empezar o avanzar en una rutina antiedad y está dispuesto a introducir un retinoide de manera gradual.",
    "skinBenefits": "",
    "howToUse": "Solo noche. Limpieza → tónico → cantidad tamaño arveja para todo el rostro → hidratante. Principiante: 2 noches/semana → días alternos → más frecuencia solo si tolera.",
    "precautions": "No aplicar sobre piel irritada. Evitar combinar al principio la misma noche con retinol/retinal adicional, peelings o exfoliantes intensos. Protector solar obligatorio al día siguiente. Evitar retinoides durante embarazo salvo indicación médica. Importante: 2% hace referencia al sistema/complejo de retinal liposomado; no debe anunciarse como “2% de retinal puro”.",
    "fullIngredients": "Panax Ginseng Root Extract, Water, Glycerin, Dipropylene Glycol, Caprylic/Capric Triglyceride, 1,2-Hexanediol, Niacinamide, Butylene Glycol, Methyl Gluceth-20, Polyglyceryl-3 Methylglucose Distearate, Hydrogenated Lecithin, Sorbitan Stearate, Ammonium Acryloyldimethyltaurate/VP Copolymer, Macadamia Ternifolia Seed Oil, Carbomer, Tromethamine, Betaine, Tocopherol, Ethylhexylglycerin, Helianthus Annuus Seed Oil, Adenosine, Disodium EDTA, Cholesterol, Polyglyceryl-10 Oleate, Brassica Campestris Sterols, Phytosteryl/Behenyl/Octyldodecyl Lauroyl Glutamate, Retinal, Silica, Aluminum/Magnesium Hydroxide Stearate, Potassium Cetyl Phosphate, Pentaerythrityl Tetra-Di-T-Butyl Hydroxyhydrocinnamate, Arctium Lappa Root Extract, Cnidium Officinale Root Extract, Dioscorea Japonica Root Extract, Paeonia Suffruticosa Root Extract, Rehmannia Chinensis Root Extract, 3-O-Ethyl Ascorbic Acid, Bakuchiol, SH-Oligopeptide-1, SH-Oligopeptide-2, SH-Polypeptide-1. incidecoder.com"
  },
  {
    "sku": "NAR-MED-PDRN-030ML",
    "name": "Medicube PDRN Pink Peptide Serum 30 ml",
    "brand": "Medicube",
    "category": "Sérum",
    "concerns": "Luminosidad · Elasticidad · Hidratación",
    "skinTypes": "Normal, seca y mixta. Grasa puede usarlo si tolera la textura. Acneica debe probarlo con cautela.",
    "description": "Sérum de enfoque regenerador cosmético y de luminosidad formulado con Sodium DNA/PDRN, niacinamida, péptidos, ácido hialurónico, colágeno y antioxidantes. Está pensado para dar apariencia más hidratada, uniforme, luminosa y elástica. Su fórmula es más compleja que otros sérums del catálogo y contiene fragancia e isopropyl myristate. MEDICUBE US",
    "audience": "Personas con piel apagada, deshidratada o que buscan apariencia más rellena y luminosa.",
    "skinBenefits": "Hidrata y mejora visualmente luminosidad, textura y elasticidad.",
    "howToUse": "Tónico → PDRN Serum → hidratante → SPF de día.",
    "precautions": "Contiene fragancia. Las pieles muy acneicas deberían hacer prueba localizada porque la fórmula contiene isopropyl myristate. El PDRN/Sodium DNA de esta versión es de origen relacionado con salmón, algo importante para clientes que buscan productos veganos.",
    "fullIngredients": "Water, Glycerin, Dipropylene Glycol, Isopropyl Myristate, Glycereth-26, Niacinamide, 1,2-Hexanediol, Sodium DNA, Butylene Glycol, Polyglycerin-3, Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Polyisobutene, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Milt Extract, Tromethamine, Glyceryl Acrylate/Acrylic Acid Copolymer, PVM/MA Copolymer, Ethylhexylglycerin, Caprylyl Glycol, Fragrance, Melia Azadirachta Leaf Extract, Adenosine, Caprylyl/Capryl Glucoside, Sorbitan Oleate, Melia Azadirachta Flower Extract, Sodium Hyaluronate, Disodium EDTA, Curcuma Longa Root Extract, Cyanocobalamin, Hydrolyzed Collagen, Ubiquinone, Ocimum Sanctum Leaf Extract, Corallina Officinalis Extract, Palmitoyl Pentapeptide-4, Palmitoyl Tripeptide-1, Palmitoyl Tetrapeptide-7, Copper Tripeptide-1, Acetyl Hexapeptide-8, Salmon Egg Extract, Atelocollagen. MEDICUBE US"
  },
  {
    "sku": "NAR-MIX-BEAN-030ML",
    "name": "Mixsoon Bean Essence 30 ml",
    "brand": "Mixsoon",
    "category": "Esencia / activo suave",
    "concerns": "Textura · Hidratación · Luminosidad",
    "skinTypes": "Todas, especialmente seca, deshidratada o áspera. Mixta y grasa también.",
    "description": "Esencia minimalista de solo siete ingredientes basada en fermentos de soja, granada, cebada y pera junto con humectantes. Puede utilizarse como esencia hidratante diariamente o como apoyo para mejorar textura mediante masaje. Su fórmula corta la hace especialmente interesante para quien no quiere una rutina cargada de muchos activos diferentes. mixsoon",
    "audience": "",
    "skinBenefits": "",
    "howToUse": "Limpieza → tónico → Bean Essence → sérum si lo hay → crema.",
    "precautions": "Si se utiliza masajeando durante más tiempo con intención exfoliante, no hace falta hacerlo diariamente. Piel sensible: empezar simplemente como esencia hidratante.",
    "fullIngredients": "Water/Aqua, Propanediol, Glycerin, Lactobacillus/Soybean Ferment Extract, Lactobacillus/Punica Granatum Fruit Ferment Extract, Saccharomyces/Barley Seed Ferment Filtrate, Lactobacillus/Pear Juice Ferment Filtrate. mixsoon"
  },
  {
    "sku": "NAR-MIX-CENT-150ML",
    "name": "Mixsoon Centella Asiatica Toner 150 ml",
    "brand": "Mixsoon",
    "category": "Tónico",
    "concerns": "Sensibilidad · Rojeces · Hidratación",
    "skinTypes": "Todas; excelente para sensible, acneica, grasa o mixta.",
    "description": "Tónico extremadamente minimalista de cuatro ingredientes diseñado alrededor del extracto de Centella asiatica. Su objetivo es añadir una capa acuosa de hidratación y calma después de limpiar, sin perfume, aceites ni una mezcla extensa de activos. Es especialmente útil cuando una persona tiene una rutina con otros tratamientos y quiere que el tónico sea sencillo. Ulta Beauty",
    "audience": "Personas sensibles o que quieren minimizar el número de ingredientes.",
    "skinBenefits": "",
    "howToUse": "Limpieza → Centella Toner → sérum → hidratante. Se pueden aplicar 2-3 capas finas si se desea más hidratación.",
    "precautions": "Muy pocas. Prueba localizada ante antecedentes de reacciones a centella.",
    "fullIngredients": "Water, Butylene Glycol, 1,2-Hexanediol, Centella Asiatica Extract. Ulta Beauty"
  },
  {
    "sku": "NAR-RDL-DOKD-200ML",
    "name": "Round Lab 1025 Dokdo Toner 200 ml",
    "brand": "Round",
    "category": "Tónico",
    "concerns": "Hidratación · Textura · Sensibilidad",
    "skinTypes": "Todas.",
    "description": "Tónico acuoso de textura muy ligera que combina agua profunda marina y minerales con humectantes, pantenol, alantoína, betaína y un sistema de exfoliación enzimática muy suave. Su función principal es hidratar y suavizar la superficie sin convertir el tónico en un tratamiento exfoliante agresivo, por lo que encaja fácilmente en rutinas de distintos tipos de piel. Round Lab",
    "audience": "Alguien que quiere hidratación ligera, piel más suave y un tónico que combine fácilmente con otros activos.",
    "skinBenefits": "",
    "howToUse": "Limpieza → Dokdo Toner → sérum → crema.",
    "precautions": "Generalmente suave. Si la barrera está gravemente irritada, cualquier exfoliación debe introducirse con prudencia.",
    "fullIngredients": "Water, Butylene Glycol, Glycerin, Pentylene Glycol, Propanediol, Chondrus Crispus Extract, Saccharum Officinarum Extract, Sea Water, 1,2-Hexanediol, Protease, Betaine, Panthenol, Ethylhexylglycerin, Allantoin, Xanthan Gum, Disodium EDTA. Round Lab"
  },
  {
    "sku": "NAR-RDL-BJMS-050ML",
    "name": "Round Lab Birch Juice Moisturizing Sunscreen 50 ml",
    "brand": "Round",
    "category": "Protector solar",
    "concerns": "Protección solar · Hidratación · Prevención manchas",
    "skinTypes": "Normal, seca y mixta especialmente. Grasa puede usarlo si le gusta un acabado hidratante.",
    "description": "Protector solar SPF50+ PA++++ de textura hidratante con filtros UV modernos y componentes como niacinamida, savia de abedul, ácido hialurónico, alantoína y dipotassium glycyrrhizate. Busca combinar protección UV alta con sensación similar a una hidratante, por lo que suele encajar especialmente bien en piel que no disfruta los protectores secos o pesados. Sephora UK",
    "audience": "",
    "skinBenefits": "",
    "howToUse": "Último paso de mañana. Aplicar una cantidad generosa y uniforme en rostro, cuello y zonas expuestas. Reaplicar durante exposición prolongada y después de sudoración/agua según las instrucciones del producto.",
    "precautions": "Ningún protector sustituye sombra, ropa o evitar exposición excesiva. Puede producir escozor ocular en algunas personas.",
    "fullIngredients": "Water, Dibutyl Adipate, Propanediol, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Polymethylsilsesquioxane, Ethylhexyl Triazone, Niacinamide, Methylene Bis-Benzotriazolyl Tetramethylbutylphenol, Coco-Caprylate/Caprate, Caprylyl Methicone, Diethylhexyl Butamido Triazone, Glycerin, 1,2-Hexanediol, Butylene Glycol, Betula Platyphylla Japonica Juice, Sodium Hyaluronate, Hyaluronic Acid, Glyceryl Glucoside, Dipotassium Glycyrrhizate, Allantoin, Portulaca Oleracea Extract, Artemisia Annua Extract, Pinus Sylvestris Leaf Oil, Anthemis Nobilis Flower Oil, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Sodium Stearoyl Glutamate, Polyacrylate Crosspolymer-6, Ethylhexylglycerin, Ascorbic Acid, Adenosine, Pentylene Glycol, Behenyl Alcohol, Poly C10-30 Alkyl Acrylate, Polyglyceryl-3 Methylglucose Distearate, Decyl Glucoside, Tromethamine, Xanthan Gum, T-Butyl Alcohol, Tocopherol, Carbomer. Sephora UK"
  },
  {
    "sku": "NAR-SK1-HYAC-050ML",
    "name": "SKIN1004 Hyalu-Cica Water-Fit Sun Serum SPF50+ PA++++ 50 ml",
    "brand": "SKIN1004",
    "category": "Protector solar",
    "concerns": "Protección solar · Hidratación · Sensibilidad",
    "skinTypes": "Todas. Muy buena opción para normal, seca y mixta; grasa también puede usarla si tolera un acabado luminoso.",
    "description": "Protector solar químico de textura sérum que combina un sistema de filtros UV de amplio espectro con centella, niacinamida y diferentes formas de ácido hialurónico. Está diseñado para ofrecer SPF50+ PA++++ sin efecto blanco marcado y con una sensación más parecida a una crema-serum hidratante que a un protector solar tradicional pesado. SKIN1004",
    "audience": "",
    "skinBenefits": "",
    "howToUse": "Último paso AM, después de crema si se necesita. Aplicar generosamente en rostro/cuello y reaplicar.",
    "precautions": "No mezclarlo dentro de la crema o maquillaje porque dificulta garantizar una capa uniforme.",
    "fullIngredients": "Water, Dibutyl Adipate, Propanediol, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Polymethylsilsesquioxane, Ethylhexyl Triazone, Methylene Bis-Benzotriazolyl Tetramethylbutylphenol, Niacinamide, Coco-Caprylate/Caprate, Caprylyl Methicone, Diethylhexyl Butamido Triazone, Glycerin, 1,2-Hexanediol, Butylene Glycol, Pentylene Glycol, Behenyl Alcohol, Poly C10-30 Alkyl Acrylate, Polyglyceryl-3 Methylglucose Distearate, Decyl Glucoside, Tromethamine, Carbomer, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Sodium Stearoyl Glutamate, Polyacrylate Crosspolymer-6, Ethylhexylglycerin, Adenosine, Xanthan Gum, Centella Asiatica Extract, T-Butyl Alcohol, Sodium Hyaluronate, Betula Platyphylla Japonica Bark Extract, Tocopherol, Hydrolyzed Hyaluronic Acid, Camellia Sinensis Leaf Extract, Ginkgo Biloba Leaf Extract, Brassica Oleracea Italica Sprout Extract, Camellia Japonica Leaf Extract, Eruca Sativa Leaf Extract, Medicago Sativa Extract, Triticum Vulgare Sprout Extract, Inositol, Hyaluronic Acid. SKIN1004"
  },
  {
    "sku": "NAR-SK1-CAFO-125ML",
    "name": "SKIN1004 Madagascar Centella Ampoule Foam 125 ml",
    "brand": "SKIN1004",
    "category": "Limpiador diario",
    "concerns": "Limpieza · Sensibilidad · Sebo",
    "skinTypes": "Normal, mixta, grasa y sensible. Seca puede probarlo vigilando tirantez.",
    "description": "Limpiador facial espumoso con pH aproximado de 5 que utiliza tensioactivos derivados principalmente de coco y añade centella, ácido hialurónico y ácido cítrico. Busca retirar grasa, suciedad y residuos sin dejar la sensación excesivamente alcalina de algunos limpiadores espumosos tradicionales. SKIN1004",
    "audience": "",
    "skinBenefits": "",
    "howToUse": "Después del aceite/bálsamo de noche o como único limpiador. Crear espuma sobre manos húmedas → rostro → masaje corto → enjuagar.",
    "precautions": "Evitar frotar durante demasiado tiempo. Si genera tirantez en piel seca, limitar a rutina nocturna.",
    "fullIngredients": "Water, Sodium Cocoyl Isethionate, Glycerin, Sodium Methyl Cocoyl Taurate, Coco-Betaine, Centella Asiatica Extract, Potassium Cocoyl Glycinate, 1,2-Hexanediol, Potassium Cocoate, Potassium Benzoate, Polyquaternium-67, Citric Acid, Sodium Chloride, Butylene Glycol, Dextrin, Theobroma Cacao Extract, Disodium EDTA, Sodium Acetate, Sodium Bicarbonate, Coptis Chinensis Root Extract, Sodium Hyaluronate, Coccinia Indica Fruit Extract, Eclipta Prostrata Extract. SKIN1004"
  },
  {
    "sku": "NAR-SK1-LCLO-200ML",
    "name": "SKIN1004 Madagascar Centella Light Cleansing Oil 200 ml",
    "brand": "SKIN1004",
    "category": "Doble limpieza",
    "concerns": "Limpieza · Sebo · Protector solar",
    "skinTypes": "Normal, seca y mixta; también puede utilizarse en grasa si tolera aceites limpiadores.",
    "description": "Aceite limpiador ligero que disuelve protector solar, maquillaje, sebo y residuos liposolubles antes del lavado acuoso. Utiliza una mezcla de emolientes y aceites vegetales junto con centella y emulsionantes para que, tras añadir agua, el producto pueda retirarse sin dejar una película de aceite pesado. SKIN1004",
    "audience": "",
    "skinBenefits": "",
    "howToUse": "Manos y rostro secos → 2-4 pumps → masaje → añadir agua → emulsionar → aclarar → limpiador acuoso.",
    "precautions": "Contiene aceites aromáticos y componentes como limonene/linalool, por lo que una piel extremadamente reactiva a fragancias debería probarlo primero.",
    "fullIngredients": "Ethylhexyl Stearate, Cetyl Ethylhexanoate, Sorbeth-30 Tetraoleate, Caprylic/Capric Triglyceride, Citrus Aurantium Bergamia Fruit Oil, Centella Asiatica Extract, Simmondsia Chinensis Seed Oil, Olea Europaea Fruit Oil, Helianthus Annuus Seed Oil, Ethylhexylglycerin, Pelargonium Graveolens Flower Oil, Rosa Damascena Flower Oil, Limonene, Linalool. SKIN1004"
  },
  {
    "sku": "NAR-SK1-PLGC-075ML",
    "name": "SKIN1004 Madagascar Centella Poremizing Light Gel Cream 75 ml",
    "brand": "SKIN1004",
    "category": "Hidratante",
    "concerns": "Poros · Sebo · Hidratación",
    "skinTypes": "Grasa y mixta principalmente. Normal también. Piel seca puede quedarse corta como única hidratante.",
    "description": "Hidratante en gel ligera diseñada especialmente para personas que quieren aportar agua y humectación sin sensación de crema pesada. Contiene centella, aloe, niacinamida, pantenol, ácido hialurónico y numerosos extractos vegetales, junto con ingredientes orientados a mejorar visualmente textura, brillo y apariencia de poros. Ulta Beauty",
    "audience": "Persona con piel grasa que dice “necesito hidratarme pero todas las cremas me dejan la cara pesada”.",
    "skinBenefits": "",
    "howToUse": "Tónico → sérum → Poremizing Gel Cream → SPF de día.",
    "precautions": "Contiene múltiples extractos botánicos. En piel hipersensible, hacer prueba localizada.",
    "fullIngredients": "Water, Propanediol, Aloe Barbadensis Leaf Extract, 1,2-Hexanediol, Niacinamide, Glycerin, Xylitol, Butylene Glycol, Centella Asiatica Extract, Carbomer, Tromethamine, Sodium Polyacryloyldimethyl Taurate, Biosaccharide Gum-1, Betaine, PVP, Sedum Sarmentosum Extract, Hydrogenated Polydecene, Ethylhexylglycerin, Adenosine, Hydroxyethylcellulose, Coccinia Indica Fruit Extract, Eclipta Prostrata Extract, Hydrolyzed Gardenia Florida Extract, Hydrolyzed Malt Extract, Disodium EDTA, Hydrolyzed Viola Tricolor Extract, Trideceth-10, Sea Water, Panthenol, Hyaluronic Acid, Hydrolyzed Hyaluronic Acid, Sodium Hyaluronate, Melia Azadirachta Flower Extract, Xylitylglucoside, Ocimum Sanctum Leaf Extract, Anhydroxylitol, Melia Azadirachta Leaf Extract, Oenothera Biennis Flower Extract, Pueraria Lobata Root Extract, Pinus Palustris Leaf Extract, Ulmus Davidiana Root Extract, Curcuma Longa Root Extract, Corallina Officinalis Extract, Castanea Crenata Shell Extract, Hamamelis Virginiana Leaf Water, Lavandula Angustifolia Flower Extract, Chamaecyparis Obtusa Water, Chenopodium Quinoa Seed Extract, Allantoin, Kaolin, Mineral Salts. Ulta Beauty"
  },
  {
    "sku": "NAR-SK1-TBCA-030ML",
    "name": "SKIN1004 Madagascar Centella Tone Brightening Capsule Ampoule 30 ml",
    "brand": "SKIN1004",
    "category": "Ampoule / activo",
    "concerns": "Manchas · Luminosidad · Post-acné",
    "skinTypes": "Normal, seca y mixta oficialmente; grasa también puede probarla por su textura ligera. Sensible: introducir poco a poco.",
    "description": "Ampolla antimanchas que combina niacinamida, ácido tranexámico, un derivado estable de vitamina C y madecassoside encapsulado con centella. Está orientada especialmente a marcas postinflamatorias, tono irregular y piel apagada, aportando simultáneamente humectación para que el tratamiento sea más fácil de incorporar en una rutina diaria. SKIN1004",
    "audience": "",
    "skinBenefits": "",
    "howToUse": "Tónico → Tone Brightening Ampoule → hidratante → SPF de mañana. Puede usarse AM y/o PM.",
    "precautions": "Resultados antimanchas requieren constancia y protección solar. Introducir gradualmente si ya se utilizan varios activos.",
    "fullIngredients": "Water, Butylene Glycol, Niacinamide, Glycerin, Tranexamic Acid, 1,2-Hexanediol, Betaine, Centella Asiatica Extract, Zea Mays Starch, Xanthan Gum, Microcrystalline Cellulose, Mannitol, Panthenol, Pentylene Glycol, Ethylhexylglycerin, Hydroxyethylcellulose, Madecassoside, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Arginine, Hydrogenated Lecithin, Xylitylglucoside, Anhydroxylitol, Xylitol, Glucose, 3-O-Ethyl Ascorbic Acid, Lactobacillus Ferment. SKIN1004"
  },
  {
    "sku": "NAR-SK1-CTON-210ML",
    "name": "SKIN1004 Madagascar Centella Toning Toner 210 ml",
    "brand": "SKIN1004",
    "category": "Tónico exfoliante suave",
    "concerns": "Textura · Poros · Luminosidad",
    "skinTypes": "Normal, mixta, grasa y seca; la marca también lo posiciona para piel sensible, aunque en personas muy reactivas conviene introducirlo lentamente.",
    "description": "Tónico acuoso que combina centella con gluconolactona, un PHA de exfoliación más gradual que muchos AHA tradicionales. Ayuda a retirar progresivamente células muertas y mejorar textura sin convertir la rutina diaria en una exfoliación agresiva, mientras ingredientes como betaína y ácido hialurónico ayudan a mantener hidratación. SKIN1004",
    "audience": "",
    "skinBenefits": "",
    "howToUse": "Después de limpiar → Toning Toner → sérum → hidratante. Aunque la marca lo contempla para uso frecuente, una piel sensible puede empezar 2-4 veces por semana.",
    "precautions": "Si utilizas otros exfoliantes fuertes, no necesitas acumular muchos en la misma rutina. SPF de día.",
    "fullIngredients": "Water, Dipropylene Glycol, Centella Asiatica Extract, 1,2-Hexanediol, Niacinamide, Sodium Citrate, Gluconolactone, Ethylhexylglycerin, Adenosine, Disodium EDTA, Dipotassium Glycyrrhizate, Betaine, Hyaluronic Acid, Carbomer, Tromethamine. SKIN1004"
  },
  {
    "sku": "NAR-SK1-PCEN-050ML",
    "name": "SKIN1004 Probio-Cica Enrich Cream 50 ml",
    "brand": "SKIN1004",
    "category": "Hidratante / barrera",
    "concerns": "Reparación barrera · Sequedad · Sensibilidad",
    "skinTypes": "Seca y normal principalmente. Mixta puede utilizarla especialmente de noche o en zonas secas. En piel muy grasa puede resultar demasiado rica.",
    "description": "Crema nutritiva de textura rica que combina centella, componentes fermentados, ceramida NP, escualano, manteca de karité, aceites y componentes propios de la centella como madecassic acid, asiaticoside y asiatic acid. Está orientada a reducir pérdida de agua y apoyar una barrera debilitada, especialmente en piel seca o sensibilizada. SKIN1004",
    "audience": "Piel seca, descamada, sobretratada o con sensación permanente de tirantez.",
    "skinBenefits": "",
    "howToUse": "Último paso: tónico → tratamiento → Probio-Cica Cream. De día continuar con SPF.",
    "precautions": "Fórmula rica. Personas muy grasas o con facilidad extrema para congestión pueden empezar con poca cantidad.",
    "fullIngredients": "Water, Glycerin, Diglycerin, 1,2-Hexanediol, Butylene Glycol, Niacinamide, Polyglyceryl-3 Distearate, Caprylic/Capric Triglyceride, Neopentyl Glycol Diheptanoate, Hydrogenated Poly(C6-14 Olefin), Isostearyl Isostearate, Pentaerythrityl Tetraisostearate, Heptyl Undecylenate, Bis-Diglyceryl Polyacyladipate-2, Glyceryl Stearate, C14-22 Alcohols, Centella Asiatica Extract, Butyrospermum Parkii Butter, Cetearyl Alcohol, Polyglyceryl-2 Stearate, Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Glyceryl Stearate Citrate, Arginine, Stearyl Alcohol, Polyisobutene, C12-20 Alkyl Glucoside, Squalane, Sodium Polyacrylate, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Carbomer, Sodium Surfactin, Hydroxystearic Acid, Ethylhexylglycerin, Adenosine, Hydrogenated Lecithin, Sorbitan Oleate, Caprylyl/Capryl Glucoside, Macadamia Ternifolia Seed Oil, Sodium Hyaluronate, Moringa Oleifera Seed Oil, Sodium Phytate, Ceramide NP, Dextrin, Theobroma Cacao Extract, Glyceryl Acrylate/Acrylic Acid Copolymer, Polyglyceryl-10 Myristate, Phytosphingosine, Stearic Acid, Lactobacillus Ferment, Madecassic Acid, Asiaticoside, Sucrose Distearate, Asiatic Acid, Phytosterols, Lauric Acid, Polyglutamic Acid. SKIN1004"
  },
  {
    "sku": "NAR-TOC-CICA-019G",
    "name": "TOCOBO Cica Cooling Sun Stick SPF50+ PA++++ 19 g",
    "brand": "TOCOBO",
    "category": "Protector solar en barra",
    "concerns": "Protección solar · Sebo · Sensibilidad",
    "skinTypes": "Normal, mixta y grasa especialmente. Puede utilizarlo piel seca, aunque posiblemente prefiera una base más hidratante debajo.",
    "description": "Protector solar sólido SPF50+ PA++++ diseñado para aplicación rápida y reaplicación durante el día. Utiliza filtros UV modernos junto con centella, derivados de ácido hialurónico, niacinamida y componentes refrescantes. Su formato en barra facilita llevarlo fuera de casa y reaplicar sin manipular una crema con las manos. Self Care Skin",
    "audience": "Personas que necesitan una forma práctica de reaplicar SPF en oficina, universidad, carro o durante actividades diarias.",
    "skinBenefits": "",
    "howToUse": "Último paso. Pasar varias veces de forma uniforme hasta cubrir completamente todas las zonas expuestas. Reaplicar durante el día.",
    "precautions": "Contiene fragancia y Mentha arvensis, por lo que una piel extremadamente reactiva puede preferir otro SPF. Evitar contacto directo con ojos. No dar solo una pasada rápida: con formatos stick es importante conseguir una capa suficiente y uniforme.",
    "fullIngredients": "Water, Coco-Caprylate/Caprate, Synthetic Wax, Dibutyl Adipate, Butyloctyl Salicylate, Butylene Glycol, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Ethylhexyl Triazone, Ozokerite, Caprylic/Capric Triglyceride, Niacinamide, Dimethicone, Polymethylsilsesquioxane, Polysilicone-15, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Centella Asiatica Root Extract, Centella Asiatica Leaf Extract, Centella Asiatica Extract, Sodium Hyaluronate, Stearalkonium Hectorite, Vinyl Dimethicone/Methicone Silsesquioxane Crosspolymer, Sodium Chloride, Glyceryl Caprylate, Caprylyl Glycol, Polyglyceryl-3 Diisostearate, Polyglyceryl-3 Polyricinoleate, Ethylhexylglycerin, Adenosine, Propylheptyl Caprylate, Triethoxycaprylylsilane, 1,2-Hexanediol, Tocopherol, Mentha Arvensis Powder, Saccharomyces Ferment, Asiaticoside, Madecassoside, Dimethylsilanol Hyaluronate, Hydrolyzed Sodium Hyaluronate, Hydrolyzed Hyaluronic Acid, Potassium Hyaluronate, Hyaluronic Acid, Sodium Hyaluronate Crosspolymer, Hydroxypropyltrimonium Hyaluronate, Sodium Hyaluronate Dimethylsilanol, Sodium Acetylated Hyaluronate, Madecassic Acid, Asiatic Acid, Fragrance, Chromium Oxide Greens. Self Care Skin"
  }
];
